apiVersion: cert-manager.io/v1alpha2
kind: Certificate
metadata:
  name: www-carbon-cc
spec:
  secretName: letsencrypt-secret-prod
  duration: 2160h # 90d
  renewBefore: 360h # 15d
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - www.carbon.cc
